version: "3.3"

services:
  db:
    image: postgres:14.4-bullseye
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: on-failure:5
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ulimits:
      nofile:
        soft: 128000
        hard: 128000
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]

  web:
    build: 
      context: .
      dockerfile: docker/dev/Dockerfile
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - .env
    volumes:
      - ./data/staticfiles:/usr/src/app/staticfiles
      - ./data/mediafiles:/usr/src/app/mediafiles
    restart: on-failure:5
    depends_on:
      db:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ulimits:
      nofile:
        soft: 128000
        hard: 128000