version: "3.3"

services:
  db:
    image: postgres:14.4-bullseye
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: on-failure:5
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ulimits:
      nofile:
        soft: 128000
        hard: 128000
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]

  web:
    build: 
      context: .
      dockerfile: docker/prod/Dockerfile
    command: uvicorn core.asgi:application --host 0.0.0.0 --port 8000
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - static_volume:/home/prism/web/staticfiles
      - media_volume:/home/prism/web/mediafiles
    env_file:
      - .env
    restart: on-failure:5
    depends_on:
      db:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ulimits:
      nofile:
        soft: 128000
        hard: 128000

volumes:
  static_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/staticfiles
  media_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/mediafiles