# Generated by Django 4.1 on 2022-08-19 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prismuser',
            name='date_registered',
        ),
    ]
