# Generated by Django 4.1 on 2022-08-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prismprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='email confirmed'),
        ),
    ]
